<a href="https://colab.research.google.com/github/armandossrecife/icc/blob/main/base_av2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import pandas as pd

In [85]:
def checa_alunos_e_listas(lista_nomes, lista_nomes_lista1, lista_nomes_lista2, lista_nomes_lista3, lista_nomes_lista4):
  # Checa os alunos que entregaram no prazo (postado nas tarefas via SIGAA) as listas l1, l2, l3 e l4
  fez_l1, fez_l2, fez_l3, fez_l4 = [], [], [], []
  for aluno in lista_nomes:
    if aluno in lista_nomes_lista1:
      fez_l1.append(1)
    else:
      fez_l1.append(0)
    if aluno in lista_nomes_lista2:
      fez_l2.append(1)
    else:
      fez_l2.append(0)
    if aluno in lista_nomes_lista3:
      fez_l3.append(1)
    else:
      fez_l3.append(0)
    if aluno in lista_nomes_lista4:
      fez_l4.append(1)
    else:
      fez_l4.append(0)
  return fez_l1, fez_l2, fez_l3, fez_l4

def cria_dicionario_alunos_listas(l1, l2, l3, l4):
  dict_listas_av2 = {
      'fez_l1':l1, 'fez_l2':l2, 'fez_l3':l3, 'fez_l4':l4
  }
  return dict_listas_av2

In [86]:
# importa dados para pre-analise da av2
!wget https://raw.githubusercontent.com/armandossrecife/icc/main/alunosicc.csv
!wget https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista1sr.csv
!wget https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista2.csv
!wget https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista3sr.csv
!wget https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista4sr.csv

--2023-03-09 15:47:53--  https://raw.githubusercontent.com/armandossrecife/icc/main/alunosicc.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 834 [text/plain]
Saving to: ‘alunosicc.csv’

alunosicc.csv       100%[===================>]     834  --.-KB/s    in 0s

2023-03-09 15:47:53 (75.0 MB/s) - ‘alunosicc.csv’ saved [834/834]

--2023-03-09 15:47:53--  https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista1sr.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 435 [text/plain]
Saving to: ‘respostas_lista1sr.csv’

respostas_lista1sr. 100%[===================>]     435  --.-KB/s    in 0s

2023-03-09 15:47:54 (22.5 MB/s) - ‘respostas_lista1sr.csv’ saved [435/435]

--2023-03-09 15:47:54--  https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 188 [text/plain]
Saving to: ‘respostas_lista2.csv’

respostas_lista2.cs 100%[===================>]     188  --.-KB/s    in 0s

2023-03-09 15:47:54 (14.4 MB/s) - ‘respostas_lista2.csv’ saved [188/188]

--2023-03-09 15:47:54--  https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista3sr.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 279 [text/plain]
Saving to: ‘respostas_lista3sr.csv’

respostas_lista3sr. 100%[===================>]     279  --.-KB/s    in 0s

2023-03-09 15:47:54 (21.7 MB/s) - ‘respostas_lista3sr.csv’ saved [279/279]

--2023-03-09 15:47:54--  https://raw.githubusercontent.com/armandossrecife/icc/main/respostas_lista4sr.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 279 [text/plain]
Saving to: ‘respostas_lista4sr.csv’

respostas_lista4sr. 100%[===================>]     279  --.-KB/s    in 0s

2023-03-09 15:47:54 (23.7 MB/s) - ‘respostas_lista4sr.csv’ saved [279/279]

In [87]:
# Ler arquivos .csv
df_alunos = pd.read_csv('alunosicc.csv')
df_alunos_lista1 = pd.read_csv('respostas_lista1sr.csv', sep=';')
df_alunos_lista2 = pd.read_csv('respostas_lista2.csv', sep=';')
df_alunos_lista3 = pd.read_csv('respostas_lista3sr.csv', sep=';')
df_alunos_lista4 = pd.read_csv('respostas_lista4sr.csv', sep=';')

# Carrega as listas de nomes e as listas da av2
lista_nomes = df_alunos['nome'].tolist()
lista_nomes_lista1 = df_alunos_lista1.Nome.tolist() 
lista_nomes_lista2 = df_alunos_lista2.Nome.tolist()
lista_nomes_lista3 = df_alunos_lista3.Nome.tolist()
lista_nomes_lista4 = df_alunos_lista4.Nome.tolist()

# Garante que os nomes estao ordenados
lista_nomes = sorted(lista_nomes)
lista_nomes_lista1 = sorted(lista_nomes_lista1)
lista_nomes_lista2 = sorted(lista_nomes_lista2)
lista_nomes_lista3 = sorted(lista_nomes_lista3)
lista_nomes_lista4 = sorted(lista_nomes_lista4)

In [88]:
l1, l2, l3, l4 = checa_alunos_e_listas(lista_nomes, lista_nomes_lista1, lista_nomes_lista2, lista_nomes_lista3, lista_nomes_lista4)
dict_listas_av2 = cria_dicionario_alunos_listas(l1, l2, l3, l4)

df_listas_av2 = pd.DataFrame(dict_listas_av2)

df_alunos[['fez_l1', 'fez_l2', 'fez_l3', 'fez_l4']] = df_listas_av2[['fez_l1', 'fez_l2', 'fez_l3', 'fez_l4']]

df_alunos['qtd_listas_entregues'] = df_alunos.fez_l1 + df_alunos.fez_l2 + df_alunos.fez_l3 + df_alunos.fez_l4

In [89]:
df_alunos

,id,matricula,nome,fez_l1,fez_l2,fez_l3,fez_l4,qtd_listas_entregues
0,1,20219027660,ANTONIO CARLOS DE FREITAS DANTAS,0,0,0,0,0
1,2,20179030600,CLERISTON DE CASTRO RAMOS,0,0,0,0,0
2,3,20229006233,DANILO DE OLIVEIRA SILVA,1,0,0,0,1
3,4,20189013095,DEIVID DE QUEIROZ BRANDAO,0,0,0,0,0
4,5,20159026388,EDMUNDO SOARES DE CARVALHO JUNIOR,1,1,1,1,4
5,6,20229008588,EUCARIO MAGALHAES PEREIRA JUNIOR,0,0,0,0,0
6,7,20229019821,GABRIELLY JHASMIN VIEIRA DA SILVA,1,0,1,1,3
7,8,20229031076,GABRIELLY LAIZ LOPES DA COSTA SILVA,1,0,0,0,1
8,9,20219011131,JHON WIGLLAFFY PORTELA VIEIRA,0,0,0,0,0
9,10,20229004945,JOAO HUMBERTO BARBOSA DA MOTA FILHO,1,1,1,1,4
10,11,20169032600,JOAO PAULO ELPIDIO RODRIGUES DO NASCIMENTO,1,0,1,1,3
11,12,20209019397,KAIQUE SAMUEL ALENCAR TORRES DANTAS,1,1,1,1,4
12,13,20219028344,LUCAS COSTA RODRIGUES,0,0,0,0,0
13,14,20199000582,MARCOS ROBERTO LIMA DE OLIVEIRA,0,0,0,0,0
14,15,20169018844,MARIANA RIBEIRO ZACARIAS DE SOUSA,0,0,0,0,0
15,16,20229012025,PALOMA CRISTINA SOUSA COSTA,1,0,1,1,3
16,17,20209021170,SAULO LEMOS DE OLIVEIRA,0,0,0,0,0
17,18,20159033168,VALDENICE LIMA DA SILVA,0,0,0,0,0